---
- name: Manage Packages
  hosts: all
  gather_facts: no
  become: yes
  vars:
    packages: []
    state: present
  tasks:
    - name: Install/Remove Packages
      apt:
        name: "{{ packages }}"
        state: "{{ state }}"
      register: result

    - name: Return Result
      debug:
        msg: "{{ result }}"
